{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "terabox-worker-service.fullname" . }}-allow-internal
  labels:
    {{- include "terabox-worker-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terabox-worker-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  # Allow internal service-to-service calls (REST)
  - from:
    - source:
        {{- if .Values.istio.authorization }}
        {{- if .Values.istio.authorization.internalCallers }}
        principals: {{ .Values.istio.authorization.internalCallers | toJson }}
        {{- end }}
        {{- end }}
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: ["/api/v1/upload/*", "/api/v1/upload/**"]
    - operation:
        ports: ["9090"]

  # Allow download endpoint for user-service
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/api/v1/upload/download"]

  # Allow public endpoints (health)
  - to:
    - operation:
        methods: ["GET"]
        paths:
          - "/health"
          - "/health/*"
          - "/api/v1/upload/media/terabox/*"
{{- end }}
