apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: terabox-worker-auth-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: terabox-worker-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/media-service"]
    to:
    - operation:
        ports: ["9090"]
