{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "terabox-worker-service.fullname" . }}-allow-internal
  labels:
    {{- include "terabox-worker-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terabox-worker-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  # Allow gRPC traffic on port 9090 from internal services
  - from:
    - source:
        {{- if .Values.istio.authorization }}
        {{- if .Values.istio.authorization.internalCallers }}
        principals: {{ .Values.istio.authorization.internalCallers | toJson }}
        {{- end }}
        {{- end }}
    to:
    - operation:
        ports: ["9090"]

  # Allow internal service-to-service calls
  - from:
    - source:
        {{- if .Values.istio.authorization }}
        {{- if .Values.istio.authorization.internalCallers }}
        principals: {{ .Values.istio.authorization.internalCallers | toJson }}
        {{- end }}
        {{- end }}
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths: 
          - "/api/v1/internal/*"
          - "/api/v1/internal/**"
    - operation:
        methods: ["POST"]
        paths:
          - "/az.fitnest.media.MediaService/*"

  # Allow public endpoints (health, docs, and media)
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        paths:
          - "/api/v1/media/*"
          - "/api/v1/media/**"
          - "/v3/api-docs/*"
          - "/v3/api-docs"
          - "/swagger-ui/*"
          - "/swagger-ui.html"
          - "/actuator/health"
          - "/actuator/health/*"
          - "/health"
{{- end }}
