{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "terabox-worker-service.fullname" . }}-allow-internal
  labels:
    {{- include "terabox-worker-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terabox-worker-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - {}
{{- end }}
