apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "terabox-worker-service.fullname" . }}-auth-policy
  labels:
    {{- include "terabox-worker-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "terabox-worker-service.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/{{ .Release.Namespace }}/sa/media-service"
    to:
    - operation:
        ports: ["9090"]
