{{- if .Values.istio.enabled}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "storage-service.fullname" . }}-allow-internal
  labels:
    {{- include "storage-service.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "storage-service.selectorLabels" . | nindent 6}}
  action: ALLOW
  rules:
    # Allow internal service-to-service calls (REST and gRPC)
    - from:
        - source:
            {{- if .Values.istio.authorization}}
              {{- if .Values.istio.authorization.internalCallers}}
              principals: {{ .Values.istio.authorization.internalCallers | toJson}}
              {{- end}}
              {{- end}}
      to:
        - operation:
            methods: [ "GET", "POST", "PUT", "DELETE" ]
            paths: [ "/api/v1/files/*", "/api/v1/files/**", "/api/v1/auth/*", "/api/v1/auth/**" ]
        - operation:
            ports: [ "9090" ]

    # Allow public endpoints (health)
    - to:
        - operation:
            methods: [ "GET" ]
            paths:
              - "/health"
              - "/health/*"
              - "/api/v1/files/media/storage/*"
  {{- end}}
