{{- if .Values.istio.enabled}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "storage-service.fullname" .}}
  labels:
    {{- include "storage-service.labels" . | nindent 4}}
spec:
  host: {{ include "storage-service.fullname" .}}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  {{- end}}
