{{- if .Values.istio.enabled}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "storage-service.fullname" . }}-mtls
  labels:
    {{- include "storage-service.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "storage-service.selectorLabels" . | nindent 6}}
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "STRICT"}}
    {{- if .Values.istio.mtls.defaultMode}}
    defaultMode: {{ .Values.istio.mtls.defaultMode}}
    {{- end}}
  {{- end}}
